git_repos = {
    "litedram" : GitRepo(url="https://github.com/enjoy-digital/",
        clone   = "regular",
        develop = True,
        sha1    = 0xef9f94a,
        branch  = "master"
    ),
    "liteeth" : GitRepo(url="https://github.com/enjoy-digital/",
        clone   = "regular",
        develop = True,
        sha1    = 0x25a4eb6,
        branch  = "master"
    ),
    "litei2c" : GitRepo(url="https://github.com/litex-hub/",
        clone   = "regular",
        develop = True,
        sha1    = 0x66214ca,
        branch  = "main"
    ),
    "liteiclink" : GitRepo(url="https://github.com/enjoy-digital/",
        clone   = "regular",
        develop = True,
        sha1    = 0x678793d,
        branch  = "master"
    ),
    "litejesd204b" : GitRepo(url="https://github.com/enjoy-digital/",
        clone   = "regular",
        develop = True,
        sha1    = 0xc2622af,
        branch  = "master"
    ),
    "litepcie" : GitRepo(url="https://github.com/enjoy-digital/",
        clone   = "regular",
        develop = True,
        sha1    = 0x73577dd,
        branch  = "master"
    ),
    "litesata" : GitRepo(url="https://github.com/enjoy-digital/",
        clone   = "regular",
        develop = True,
        sha1    = 0xc4baa46,
        branch  = "master"
    ),
    "litescope" : GitRepo(url="https://github.com/enjoy-digital/",
        clone   = "regular",
        develop = True,
        sha1    = 0x2dafca2,
        branch  = "master"
    ),
    "litesdcard" : GitRepo(url="https://github.com/enjoy-digital/",
        clone   = "regular",
        develop = True,
        sha1    = 0x80a3004,
        branch  = "master"
    ),
    "litespi" : GitRepo(url="https://github.com/litex-hub/",
        clone   = "regular",
        develop = True,
        sha1    = 0xc67f8db,
        branch  = "master"
    ),
    "litex" : GitRepo(url="https://github.com/enjoy-digital/",
        clone   = "regular",
        develop = True,
        sha1    = 0x9fea53b,
        branch  = "master"
    ),
    "litex-boards" : GitRepo(url="https://github.com/litex-hub/",
        clone   = "regular",
        develop = True,
        sha1    = 0x801fc7d,
        branch  = "master"
    ),
    "migen" : GitRepo(url="https://git.m-labs.hk/M-Labs/",
        clone   = "regular",
        develop = True,
        sha1    = 0x44e5627,
        branch  = "master"
    ),
    "pythondata-cpu-lm32" : GitRepo(url="https://github.com/litex-hub/",
        clone   = "regular",
        develop = True,
        sha1    = 0x594f206,
        branch  = "master"
    ),
    "pythondata-cpu-minerva" : GitRepo(url="https://github.com/litex-hub/",
        clone   = "regular",
        develop = True,
        sha1    = 0x8db577a,
        branch  = "master"
    ),
    "pythondata-cpu-mor1kx" : GitRepo(url="https://github.com/litex-hub/",
        clone   = "regular",
        develop = True,
        sha1    = 0x4b9d59b,
        branch  = "master"
    ),
    "pythondata-cpu-naxriscv" : GitRepo(url="https://github.com/litex-hub/",
        clone   = "regular",
        develop = True,
        sha1    = 0x975694c,
        branch  = "main"
    ),
    "pythondata-cpu-sentinel" : GitRepo(url="https://github.com/litex-hub/",
        clone   = "recursive",
        develop = True,
        sha1    = 0x83f93b6,
        branch  = "main"
    ),
    "pythondata-cpu-serv" : GitRepo(url="https://github.com/litex-hub/",
        clone   = "regular",
        develop = True,
        sha1    = 0xcdede3b,
        branch  = "master"
    ),
    "pythondata-cpu-vexiiriscv" : GitRepo(url="https://github.com/litex-hub/",
        clone   = "regular",
        develop = True,
        sha1    = 0x7f71c79,
        branch  = "main"
    ),
    "pythondata-cpu-vexriscv" : GitRepo(url="https://github.com/litex-hub/",
        clone   = "recursive",
        develop = True,
        sha1    = 0x1979a64,
        branch  = "master"
    ),
    "pythondata-cpu-vexriscv-smp" : GitRepo(url="https://github.com/litex-hub/",
        clone   = "recursive",
        develop = True,
        sha1    = 0x0a97182,
        branch  = "master"
    ),
    "pythondata-misc-tapcfg" : GitRepo(url="https://github.com/litex-hub/",
        clone   = "regular",
        develop = True,
        sha1    = 0xfbcb024,
        branch  = "master"
    ),
    "pythondata-misc-usb_ohci" : GitRepo(url="https://github.com/litex-hub/",
        clone   = "recursive",
        develop = True,
        sha1    = 0xf141aed,
        branch  = "master"
    ),
    "pythondata-software-compiler_rt" : GitRepo(url="https://github.com/litex-hub/",
        clone   = "regular",
        develop = True,
        sha1    = 0xfcb0324,
        branch  = "master"
    ),
    "pythondata-software-picolibc" : GitRepo(url="https://github.com/litex-hub/",
        clone   = "recursive",
        develop = True,
        sha1    = 0x4dbc2c3,
        branch  = "master"
    ),
}
