lms7_trx_files = [
    # SPI.
    "LimeSDR-Mini_lms7_trx/src/spi/cfg_top.vhd",
    "LimeSDR-Mini_lms7_trx/src/spi/fpgacfg.vhd",
    "LimeSDR-Mini_lms7_trx/src/spi/fpgacfg_pkg.vhd",
    "LimeSDR-Mini_lms7_trx/src/spi/mcfg_components.vhd",
    "LimeSDR-Mini_lms7_trx/src/spi/mcfg32wm_fsm.vhd",
    "LimeSDR-Mini_lms7_trx/src/spi/mem_package.vhd",
    "LimeSDR-Mini_lms7_trx/src/spi/periphcfg.vhd",
    "LimeSDR-Mini_lms7_trx/src/spi/periphcfg_pkg.vhd",
    "LimeSDR-Mini_lms7_trx/src/spi/pllcfg_pkg.vhd",
    "LimeSDR-Mini_lms7_trx/src/spi/tstcfg.vhd",
    "LimeSDR-Mini_lms7_trx/src/spi/tstcfg_pkg.vhd",

    "LimeSDR-Mini_lms7_trx/src/packages/synth/FIFO_PACK.vhd",

    # Revision.
    "LimeSDR-Mini_lms7_trx/src/revision/revision.vhd",

    # PLL.
    "LimeSDR-Mini_lms7_trx/src/pll_top/synth/pll_top.vhd",
    "LimeSDR-Mini_lms7_trx/src/spi/pllcfg.vhd",

    "LimeSDR-Mini_lms7_trx/src/general/sync_reg.vhd",

    "LimeSDR-Mini_lms7_trx/src/general_periph/synth/general_periph_top.vhd",
    "LimeSDR-Mini_lms7_trx/src/general/alive.vhd",
    "LimeSDR-Mini_lms7_trx/src/general/FX3_LED_ctrl.vhd",
    "LimeSDR-Mini_lms7_trx/src/general/FPGA_LED2_ctrl.vhd",
    "LimeSDR-Mini_lms7_trx/src/general/FPGA_LED_cntrl.vhd",
    "LimeSDR-Mini_lms7_trx/src/general/gpio_ctrl_top.vhd",
    "LimeSDR-Mini_lms7_trx/src/general/gpio_ctrl.vhd",
    "LimeSDR-Mini_lms7_trx/src/general/general_pkg.vhd",
    "LimeSDR-Mini_lms7_trx/src/self_test/transition_count.vhd",
    "LimeSDR-Mini_lms7_trx/src/self_test/singl_clk_with_ref_test.vhd",
    "LimeSDR-Mini_lms7_trx/src/self_test/clk_with_ref_test.vhd",
    "LimeSDR-Mini_lms7_trx/src/self_test/clk_no_ref_test.vhd",
    "LimeSDR-Mini_lms7_trx/mico32_patform/platform1/soc/platform1_vhd.vhd",
    "LimeSDR-Mini_lms7_trx/mico32_patform/platform1/soc/platform1_top.v",
    "LimeSDR-Mini_lms7_trx/src/rxtx_top/synth/rxtx_top.vhd",
    "LimeSDR-Mini_lms7_trx/src/tx_path_top/tx_path/synth/sync_fifo_rw.vhd",
    "LimeSDR-Mini_lms7_trx/src/tx_path_top/tx_path/synth/tx_path_top.vhd",
    "LimeSDR-Mini_lms7_trx/src/tx_path_top/pulse_gen/synth/pulse_gen.vhd",
    "LimeSDR-Mini_lms7_trx/src/tx_path_top/pct_separate/synth/one_pct_fifo.vhd",
    "LimeSDR-Mini_lms7_trx/src/tx_path_top/pct_separate/synth/pct_separate_fsm.vhd",
    "LimeSDR-Mini_lms7_trx/src/tx_path_top/packets2data/synth/p2d_rd.vhd",
    "LimeSDR-Mini_lms7_trx/src/tx_path_top/packets2data/synth/p2d_rd_fsm.vhd",
    "LimeSDR-Mini_lms7_trx/src/tx_path_top/packets2data/synth/p2d_sync_fsm.vhd",
    "LimeSDR-Mini_lms7_trx/src/tx_path_top/packets2data/synth/p2d_wr_fsm.vhd",
    "LimeSDR-Mini_lms7_trx/src/tx_path_top/packets2data/synth/packets2data.vhd",
    "LimeSDR-Mini_lms7_trx/src/tx_path_top/packets2data/synth/packets2data_top.vhd",
    "LimeSDR-Mini_lms7_trx/src/tx_path_top/handshake_sync/synth/handshake_sync.vhd",
    "LimeSDR-Mini_lms7_trx/src/tx_path_top/fifo2diq/synth/fifo2diq.vhd",
    "LimeSDR-Mini_lms7_trx/src/tx_path_top/fifo2diq/synth/txiq.vhd",
    "LimeSDR-Mini_lms7_trx/src/tx_path_top/fifo2diq/synth/txiq_ctrl.vhd",
    "LimeSDR-Mini_lms7_trx/src/tx_path_top/bit_unpack/synth/bit_unpack_64.vhd",
    "LimeSDR-Mini_lms7_trx/src/tx_path_top/bit_unpack/synth/unpack_64_to_48.vhd",
    "LimeSDR-Mini_lms7_trx/src/tx_path_top/bit_unpack/synth/unpack_64_to_56.vhd",
    "LimeSDR-Mini_lms7_trx/src/tx_path_top/bit_unpack/synth/unpack_64_to_64.vhd",
    "LimeSDR-Mini_lms7_trx/src/rx_path_top/bit_pack/synth/bit_pack.vhd",
    "LimeSDR-Mini_lms7_trx/src/rx_path_top/bit_pack/synth/pack_48_to_64.vhd",
    "LimeSDR-Mini_lms7_trx/src/rx_path_top/bit_pack/synth/pack_56_to_64.vhd",
    "LimeSDR-Mini_lms7_trx/src/rx_path_top/smpl_cmp/synth/smpl_cmp.vhd",
    "LimeSDR-Mini_lms7_trx/src/rx_path_top/rx_path/synth/rx_path_top.vhd",
    "LimeSDR-Mini_lms7_trx/src/rx_path_top/diq2fifo/synth/diq2fifo.vhd",
    "LimeSDR-Mini_lms7_trx/src/rx_path_top/diq2fifo/synth/rxiq.vhd",
    "LimeSDR-Mini_lms7_trx/src/rx_path_top/diq2fifo/synth/rxiq_mimo.vhd",
    "LimeSDR-Mini_lms7_trx/src/rx_path_top/diq2fifo/synth/rxiq_mimo_ddr.vhd",
    "LimeSDR-Mini_lms7_trx/src/rx_path_top/diq2fifo/synth/rxiq_pulse_ddr.vhd",
    "LimeSDR-Mini_lms7_trx/src/rx_path_top/diq2fifo/synth/rxiq_siso.vhd",
    "LimeSDR-Mini_lms7_trx/src/rx_path_top/diq2fifo/synth/rxiq_siso_ddr.vhd",
    "LimeSDR-Mini_lms7_trx/src/rx_path_top/diq2fifo/synth/rxiq_siso_sdr.vhd",
    "LimeSDR-Mini_lms7_trx/src/rx_path_top/diq2fifo/synth/test_data_dd.vhd",
    "LimeSDR-Mini_lms7_trx/src/rx_path_top/data2packets/synth/data2packets.vhd",
    "LimeSDR-Mini_lms7_trx/src/rx_path_top/data2packets/synth/data2packets_fsm.vhd",
    "LimeSDR-Mini_lms7_trx/src/rx_path_top/data2packets/synth/data2packets_top.vhd",
    "LimeSDR-Mini_lms7_trx/src/general/bus_sync_reg.vhd",
    "LimeSDR-Mini_lms7_trx/src/rx_path_top/smpl_cnt/synth/iq_smpl_cnt.vhd",
    "LimeSDR-Mini_lms7_trx/src/rx_path_top/smpl_cnt/synth/smpl_cnt.vhd",
    "LimeSDR-Mini_lms7_trx/src/altera_inst/lpm_cnt_inst.vhd",
    "LimeSDR-Mini_lms7_trx/src/altera_inst/fifo_inst.vhd",
    "LimeSDR-Mini_lms7_trx/src/txiqmux/synth/txiqmux.vhd",
    "LimeSDR-Mini_lms7_trx/src/txiqmux/synth/txiq_tst_ptrn.vhd",
    "LimeSDR-Mini_lms7_trx/src/altera_inst/lpm_compare_inst.vhd",
    "LimeSDR-Mini_lms7_trx/src/delayf_ctrl/delay_ctrl_fsm.vhd",
    "LimeSDR-Mini_lms7_trx/src/delayf_ctrl/delay_ctrl_top.vhd",
    "LimeSDR-Mini_lms7_trx/src/delayf_ctrl/delayf_ctrl.vhd",
    "LimeSDR-Mini_lms7_trx/src/tx_path_top/fifo2diq/synth/edge_delay.vhd",
    "LimeSDR-Mini_lms7_trx/src/general/busy_delay.vhd",
    "LimeSDR-Mini_lms7_trx/src/cpu/cpu.vhd",
]

lms7_trx_ips = [
    "LimeSDR-Mini_lms7_trx/proj/ip/fifodc_w64x256_r64/fifodc_w64x256_r64.sbx",
    "LimeSDR-Mini_lms7_trx/proj/ip/fifo_dc/fifo_dc_64x256x64_outreg/fifo_dc_64x256x64_outreg.sbx",
    "LimeSDR-Mini_lms7_trx/proj/ip/fifo_dc/fifodc_w128x256_r128_outreg/fifodc_w128x256_r128_outreg.sbx",
    "LimeSDR-Mini_lms7_trx/proj/ip/fifo_dc/fifodc_w64x256_r64_outreg/fifodc_w64x256_r64_outreg.sbx",
    "LimeSDR-Mini_lms7_trx/proj/ip/fifo_dc/fifodc_w128x256_r64_outreg/fifodc_w128x256_r64_outreg.sbx",
    "LimeSDR-Mini_lms7_trx/proj/ip/fifo_dc/fifodc_w48x1024_r48_outreg/fifodc_w48x1024_r48_outreg.sbx",
    "LimeSDR-Mini_lms7_trx/proj/ip/fifo_dc/fifodc_w32x1024_r128/fifodc_w32x1024_r128.sbx",
    "LimeSDR-Mini_lms7_trx/proj/ip/fifo_dc/fifodc_w128x256_r128/fifodc_w128x256_r128.sbx",
    "LimeSDR-Mini_lms7_trx/proj/ip/fifo_dc/fifodc_w128x256_r64/fifodc_w128x256_r64.sbx",
    "LimeSDR-Mini_lms7_trx/proj/ip/fifodc_w64x256_r64/fifodc_w64x256_r64.sbx",
    "LimeSDR-Mini_lms7_trx/proj/ip/fifo_dc/fifodc_w48x1024_r48/fifodc_w48x1024_r48.sbx",
    "LimeSDR-Mini_lms7_trx/proj/ip/fifo_dc/fifodc_w32x1024_r128_outreg/fifodc_w32x1024_r128_outreg.sbx",
    "LimeSDR-Mini_lms7_trx/proj/ip/fifo_dc/fifodc_w64x2024_r32/fifodc_w64x2024_r32.sbx",
    "LimeSDR-Mini_lms7_trx/proj/ip/fifo_dc/fifodc_w32x256_r32_outreg/fifodc_w32x256_r32_outreg.sbx",
    "LimeSDR-Mini_lms7_trx/proj/ip/fifo_dc/fifodc_w32x256_r32/fifodc_w32x256_r32.sbx",
]
